MLFLOW_TRACKING_URI: http://127.0.0.1:1234
model: yolov8n.pt
data: coco8.yaml
epochs: 5
patience: 50
batch: 4
imgsz: 1280
save: False
cache: ram
device: 0
project: mlflow-yolosam # name should start by "mlflow-"
name: mlflow-yolosam # name should start by "mlflow-"
pretrained: True
optimizer: SGD
seed: 0
deterministic: True
lr0: 0.01
verbose: True
val : True
yolosam : True